### ISSUE TITLE
Questions on 300VW dataset.

### ISSUE THREAD

**Issue by Zealoe** [grigorisg9gr/robust_deformable_face_tracking#2]
Sorry to disturb,  but I have a problem with 300VW dataset.
The offical web said that it contains 300 videos. But the file I download from the web only contains 114 video clips.
What's the problem, thanks!

**Comment by grigorisg9gr** [comment]
Hi, 
this is the total number of videos (the workshop was named 300videos in the wild as a follow up to earlier work, the site does not mention there are 300 videos). Feel free to read the actual paper paper: https://ibug.doc.ic.ac.uk/media/uploads/documents/shen_the_first_facial_iccv_2015_paper.pdf
